# Generated by Django 3.0.4 on 2020-08-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='height',
            field=models.IntegerField(default=0, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='media',
            name='width',
            field=models.IntegerField(default=0, verbose_name='width'),
        ),
    ]
