# Generated by Django 3.0.4 on 2020-08-08 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='about_me', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('page_title', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_me',
            },
        ),
    ]
