version: "3.4"

volumes:
  django-blog.db.volume:
    name: django-blog.db.volume
  redisdata:

services:
  nginx:
    image: nginx:1.13
    container_name: django-blog.nginx
    ports:
      - "8000:8000"
    volumes:
      - ./backend/nginx/conf:/etc/nginx/conf.d
      - ./backend/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./backend/django/static:/static
    depends_on:
      - django
  db:
    image: mysql:5.7
    container_name: django-blog.db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - .dbdata:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d
      - ./backend/my.cnf:/etc/mysql/conf.d/my.cnf
  redis:
    restart: always
    image: redis
    volumes:
      - redisdata:/data
  django:
    build:
      context: ./backend/django
    container_name: django-blog.django
    volumes:
      - ./backend/django:/app
    command: uwsgi --socket :8001 --py-autoreload 1 --ini /app/django.ini
    expose:
      - "8001"
    depends_on:
      - db
