# Generated by Django 2.2 on 2020-03-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
