# Generated by Django 2.2 on 2020-03-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200304_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
