CREATE DATABASE IF NOT EXISTS mydeta CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'pass';
GRANT ALL PRIVILEGES ON mydeta.* TO 'user'@'%';

FLUSH PRIVILEGES;