version: 2.1
executors:
  my-executor:
    working_directory: ~/project/frontend
    docker:
      - image: circleci/python:3-node
jobs:
  frontend-test:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: pwd
          command: pwd && ls -la
          working_directory: frontend
      - restore_cache:
          name: Yarn cache restore
          keys:
            - yarn-packages-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile
          # working_directory: frontend
      - save_cache:
          name: Save yarn cache
          key: yarn-packages-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ~/project/.cache/yarn
            - ~/project/frontend/node_modules
            # - ~/.cache/yarn
      - run:
          name: test
          command: yarn test
          # working_directory: frontend
workflows:
  version: 2
  frontend-build-and-test:
    jobs:
      - frontend-test
