version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:3-node
jobs:
  frontend-test:
    working_directory: ~/frontend
    executor: my-executor
    steps:
      - checkout
      - run:
          name: pwd
          command: pwd && ls -la
      - restore_cache:
          name: Yarn cache restore
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: cd frontend && yarn install --frozen-lockfile
      - save_cache:
          name: Save yarn cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/frontend/node_modules
            # - ~/.cache/yarn
      - run:
          name: test
          command: cd frontend && yarn test
workflows:
  version: 2
  frontend-build-and-test:
    jobs:
      - frontend-test
