version: 2.1
executors:
  my-executor:
    working_directory: ~/project
    docker:
      - image: circleci/python:3-node
jobs:
  backend-test:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          key: v1-pip-cache-{{ .Branch }}-{{ checksum "backend/django/requirements.txt" }}
      - run:
          name: pip install
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
          working_directory: backend/django
      - save_cache:
          paths:
            - "venv"
          key: v1-pip-cache-{{ .Branch }}-{{ checksum "backend/django/requirements.txt" }}
      - run:
          name: pytest
          command: |
            . venv/bin/activate
            pytest --cov
          working_directory: backend/django
      - store_artifacts:
          path: test-reports/
          destination: python_app
  frontend-test:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          name: Yarn cache restore
          keys:
            - v1-yarn-cache-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile
          working_directory: frontend
      - save_cache:
          name: Save yarn cache
          key: v1-yarn-cache-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ~/project/.cache/yarn
            - ~/project/frontend/node_modules
            # - ~/.cache/yarn
      - run:
          name: yarn test
          command: yarn test
          working_directory: frontend
workflows:
  version: 2
  build-and-test:
    jobs:
      - backend-test
      - frontend-test
