version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:3-node
# orbs:
#   node: circleci/python:3-node 
jobs:
  frontend-test:
    executor:
      name: my-executor
    steps:
      - checkout
      - restore_cache:
        name: Yarn cache restore
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
        name: yarn install
        command: yarn install --frozen-lockfile
      - save_cache:
        name: Save yarn cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
      - run:
        name: test
        command: yarn test
    # executor:
    #   name: node/default
    # steps:
    #   - checkout
    #   - node/with-cache:
    #       steps:
    #         - run: yarn install
    #         - run: yarn test
workflows:
  version: 2.1
  frontend-build-and-test:
    jobs:
      - frontend-test