# Generated by Django 3.0.4 on 2020-11-22 14:58

from django.db import migrations, models
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=site_settings.models.get_file_path, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to=site_settings.models.get_file_path, verbose_name='main_image'),
        ),
    ]
