# Generated by Django 3.0.4 on 2020-04-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200410_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plain_content',
            field=models.TextField(blank=True, null=True, verbose_name='plain_content'),
        ),
    ]
