# Generated by Django 3.0.4 on 2020-03-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200307_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
