# Generated by Django 3.0.4 on 2020-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userprofile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
